export const MEDIUM_BREAKPOINT = 1650
export const SECOND_MEDIUM_BREAKPOINT = 1400
export const SMALL_BREAKPOINT = 1150

export const HEADER_HEIGHT = 0
export const HEADER_HEIGHT_MEDIUM = 69
export const HEADER_HEIGHT_SMALL = 55

export const PORTFOLIO_IMAGE_WIDTH = 404
export const PORTFOLIO_IMAGE_WIDTH_SECOND_MEDIUM = 350
export const PORTFOLIO_IMAGE_WIDTH_SMALL = 338

export const BEAT_NUMBER = 2100
